name: Fire Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  call:
    uses: ./.github/workflows/ship-impl.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
